### ISSUE TITLE
tutorials/Battery Charger.md

### ISSUE THREAD

**Issue by tonywye** [espruino/EspruinoDocs#230]
I dont think the line "Add a wire from Espruino's GND pin straight down to the bottom - row of pins" is correct. Certainly the picture does not show this. 

There is no connection to the bottom row of pins. 
I cant see a connection from GND on PICO to GND on the LCD

**Comment by gfwilliams** [comment]
It is correct - however the wire is hidden under the LCD screen. I've just updated the docs (not on the main espruino site yet) to explain that a bit better.

You don't need GND on the LCD - because it draws so little power, it can be powered off the GPIO, saving a few wires. The line `B3.write(0); // GND` in the code adds GND to the LCD.
