### ISSUE TITLE
tutorials/Quick Start BLE.md

### ISSUE THREAD

**Issue by scheib** [espruino/EspruinoDocs#440]
Oh no, pixl.js arrived without a battery, and documentation doesn't state precisely which kind to pop into it.

**Comment by wilberforce** [comment]
I believe it's the same as the puck.js - CR2032

**Comment by gfwilliams** [comment]
Yep, CR2032. Thanks for the heads up - I'll add that!

**Comment by gfwilliams** [comment]
Actually it does seem to say in the third line down on http://www.espruino.com/Quick+Start+BLE#pixljs

Is it unclear that CR2032 is the battery type?

The whole battery thing is annoying. I'd have loved to have shipped them with batteries but shipping rules are a pain, especially if there's more than one in a pack. I could just about get away with it with Puck.js because the whole thing is covered and in a box, but if it was a separate battery I'd probably have issues.

**Comment by scheib** [comment]
Don't know how I misread that page /shrug/.  Looks good to me as it is now.
