### ISSUE TITLE
tutorials/Ikea Eneby Speaker Controller.md

### ISSUE THREAD

**Issue by sohnemann** [espruino/EspruinoDocs#507]
Hi there,

thank you very much for this detailed tutorial.

This is not really an issue, but more of a general IoT-question.

As I'm new to IoT-devices, I would like to ask if there is any way to 
just set the volume to a higher default when turning the Eneby on?

I really don't need any remote features, so would a cheaper controller 
e.g. an ESP8266 also suffice to accomplish this use case?

Any help on this is much appreciated.

Thanks
sohnemann

**Comment by gfwilliams** [comment]
Hi - yes, you could use another microcontroller if you just want to set the volume. You could look at the power LED to see when it powered on and then set the volume accordingly.

It'd need to be 3.3v, and it's possible you would find that an ESP8266 used too much power.

I think a lot of it comes down to how much time/effort you want to spend in order to save £10.
